# 자바 버전
language: java
jdk:
  - openjdk8

# master 브랜치에 푸시 했을 때만 실행
branches:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - hyeoo1004@gmail.com
